name: Build PowerShell EXE

on:
  push:
    branches:
      - main

jobs:
  build_exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PS2EXE
      run: |
        Install-Module -Name ps2exe -Force

    - name: Convert PowerShell script to EXE
      run: |
        ps2exe .\scripts\RunTask.ps1 .\scripts\RunTask.exe

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: ./scripts/RunTask.exe
