name: Build and Release PowerShell EXE

on:
  push:
    tags:
      - "v*.*.*"  # Runs when a version tag like "v1.0.1" is pushed

permissions:
  contents: write  # Grants permission to create releases

jobs:
  build_exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Install PS2EXE
      run: |
        Invoke-WebRequest -Uri "https://github.com/MScholtes/PS2EXE/releases/download/v1.0.15/ps2exe.zip" -OutFile "ps2exe.zip"
        Expand-Archive -Path "ps2exe.zip" -DestinationPath "C:\ps2exe" -Force
        $env:PATH += ";C:\ps2exe"

    - name: Convert PowerShell script to EXE
      run: |
        C:\ps2exe\ps2exe.ps1 .\scripts\RunTask.ps1 .\scripts\RunTask.exe

    - name: Upload EXE as an artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: ./scripts/RunTask.exe

    - name: Create a GitHub Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}  # Uses the pushed Git tag as the release version
        body: "Automatically generated release with compiled EXE."
        draft: false
        prerelease: false
        files: ./scripts/RunTask.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
