name: Build and Release PowerShell EXE

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter release version (e.g., v1.0.1)"
        required: true

jobs:
  build_exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PS2EXE
      run: |
        Install-Module -Name ps2exe -Force

    - name: Convert PowerShell script to EXE
      run: |
        ps2exe .\scripts\RunTask.ps1 .\scripts\RunTask.exe

    - name: Upload EXE as an artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: ./scripts/RunTask.exe

    - name: Create a GitHub Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: "Release ${{ github.event.inputs.version }}"
        body: "This is an automated release containing the compiled EXE."
        draft: false
        prerelease: false
        files: ./scripts/RunTask.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
