name: Build and Release PowerShell EXE

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build_exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PS2EXE manually
      run: |
        New-Item -ItemType Directory -Path "C:\ps2exe" -Force
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/MScholtes/PS2EXE/master/ps2exe.ps1" -OutFile "C:\ps2exe\ps2exe.ps1"
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/MScholtes/PS2EXE/master/ps2exe.psm1" -OutFile "C:\ps2exe\ps2exe.psm1"
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/MScholtes/PS2EXE/master/ps2exe.exe" -OutFile "C:\ps2exe\ps2exe.exe"
        $env:PATH += ";C:\ps2exe"

    - name: Convert PowerShell script to EXE
      run: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\ps2exe\ps2exe.ps1" .\scripts\RunTask.ps1 .\scripts\RunTask.exe

    - name: Upload EXE as Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./scripts/RunTask.exe
        asset_name: RunTask.exe
        asset_content_type: application/octet-stream
