name: Build and Release PowerShell EXE

on:
  release:
    types: [created]  # ✅ Runs after a GitHub release is created

permissions:
  contents: write  # ✅ Ensures GitHub Actions can upload release assets

jobs:
  build_exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PS2EXE
      run: |
        Install-Module -Name ps2exe -Force

    - name: Convert PowerShell script to EXE
      run: |
        ps2exe .\scripts\RunTask.ps1 .\scripts\RunTask.exe

    - name: Upload EXE as Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Uses GitHub token for an existing release
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./scripts/RunTask.exe
        asset_name: RunTask.exe
        asset_content_type: application/octet-stream
